### ISSUE TITLE
Command line options aren't recognised

### ISSUE THREAD

**Issue by drdaz** [artemv/circleci-step-outputter#22]
Running this line:

`circle-step-outputter --repoSlug="parse-community/Parse-SDK-iOS-OSX" --buildnum=2952`

Results in the --help output. I've tried setting the appropriate environment vars for the user and repo instead of using command line options, and get a little further, but since I can't specify 'step' in this way, still no result :(

```
Darrens-MacBook-Pro:~ drdaz$ CIRCLE_BUILD_NUM=2952 CIRCLE_PROJECT_USERNAME="parse-community" CIRCLE_PROJECT_REPONAME="Parse-SDK-iOS-OSX" circle-step-outputter --stepName="bundle exec rake test:macos"
querying "https://circleci.com/api/v1.1/project/github/parse-community/Parse-SDK-iOS-OSX/2952" for meta
You specified invalid step identifier, "npm test". Steps available in build: ["Spin up Environment","Checkout code","git submodule update --init --recursive\ngem install bundler\nbundle install\n","bundle exec rake test:macos","Uploading test results"]
```

macOS 10.14.5, node 12.4.0, npm 6.10.0.

**Comment by artemv** [comment]
Hi @drdaz, it was just a casing issue in your args - need to be `buildNum`, not `buildnum`:
```
circle-step-outputter --repoSlug="parse-community/Parse-SDK-iOS-OSX" --buildNum=2952 --step="macos"
```
