### ISSUE TITLE
Specifying step

### ISSUE THREAD

**Issue by dickmao** [artemv/circleci-step-outputter#5]
I noticed it is sufficient to specify the prefix of a step to get its output.  So, for a longwinded step such as `set -x\nsource aliases.sh\necho foo`, I merely needed to say `--step set`.  Is this intentional and can it be documented?

**Comment by artemv** [comment]
Hi @dickmao, yeah, this is intentional. The docs are incomplete, you're right - PR is welcome, otherwise I hope I'll do it at some point )

**Comment by artemv** [comment]
docs updated
